### ISSUE TITLE
error message "The debian package doesn't contain all needed informations."

### ISSUE THREAD

**Issue by stef204** [Asher256/archalien#3]
Getting:

```
% archalien tkrat_2.2cvs20100105-true-dfsg-6_amd64.deb
Conversion of tkrat_2.2cvs20100105-true-dfsg-6_amd64.deb...

The debian package doesn't contain all needed informations.
The variable 'version' is empty.
```

Any suggestions as how to fix?  Is this related to pull request?

Link to deb file:
[http://ftp.de.debian.org/debian/pool/main/t/tkrat/tkrat_2.2cvs20100105-true-dfsg-6_amd64.deb](url)

**Comment by Asher256** [comment]
Thank you for the report. I fixed the bug in the 'master' branch.

**Comment by stef204** [comment]
fixed, thanks.
