### ISSUE TITLE
Archalien does not work with xz compression (default for deb-dpkg)

### ISSUE THREAD

**Issue by x5ERZzk** [Asher256/archalien#5]
Hello,
I have installed dpkg package and followed steps from https://gnu-linux.org/quickly-edit-a-deb-package.html
However when I ran archalien on resulting deb package it complained it cannot open control.tar.gz (control.tar.xz was inside the .deb archive).
Thanks for your work!

**Comment by Jakeukalane** [comment]
Hello @x5ERZzk

I replaced                   (os.path.join(input_tmpd, 'control.tar.gz'))) with                   (os.path.join(input_tmpd, 'control.tar.xz'))) in archalien.py. In my file it was the line 266. And it works, or at least, the conversion is done... Cannot guarantee that the package installs...

**Comment by Asher256** [comment]
@x5ERZzk The latest version of archalien supports "control.tar.xz".
