### ISSUE TITLE
Archalien does not support line break in the Description field of a control file

### ISSUE THREAD

**Issue by x5ERZzk** [Asher256/archalien#6]
Hello,
I have tried to convert a deb package from https://www.zecwallet.co/#download - https://github.com/adityapk00/zecwallet-lite/releases/download/v1.2.2/Zecwallet_Lite_1.2.2_amd64.deb but archalien refused and quit with the message:
> The debian package doesn't contain all needed informations.
> The variable 'description' is empty.

Thanks in advance

Best wishes

**Comment by JoaquinDecima** [comment]
**Getting:**

``` bash
Conversion of streamlabels_0.3.8_amd64.deb...

The debian package doesn't contain all needed informations.
The variable 'description' is empty.
```

Any suggestions as how to fix? Is this related to pull request?

**DEB URL:**
https://s3-us-west-2.amazonaws.com/streamlabs-electron/streamlabels_0.3.8_amd64.deb

**Comment by JoaquinDecima** [comment]
I _"solved"_ it simply by eliminating the line that ends the process when the data is missing (at the risk that it may go wrong). If you want to do this, it is done by **removing line 186** from _archalien.py_

This generated the corresponding file and **I was** able to install it. I understand that it may _"not be stable"_ but I'm not sure.
